apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: feedback
spec:
  selector:
    app: feedback-flask
  ports:
  - protocol: "TCP"
    port: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-flask
  namespace : feedback
spec:
  selector:
    matchLabels:
      app: feedback-flask
  replicas: 1
  template:
    metadata:
      labels:
        app: feedback-flask
    spec:
      containers:
      - name: feedback-flask
        image: pcsruniraj/feedback-flask:cov01
        imagePullPolicy: Always
        ports:
        - containerPort: 80
